version: '3'
networks:
  reu.net:
    driver: bridge
services:
  #####################################################
  # API SERVICES
  #####################################################

  #######################################
  ###  Reunionou Service
  ###  api.reunionou.local
  #######################################

  api.reunionou:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.reunionou.local
      - VHOST_DOCROOT=/var/www/public
    ports:
      - '19080:80'
      - '19043:443'
    volumes:
      - './reu_reunionou_service:/var/www'
    working_dir: /var/www/
    networks:
      - reu.net
    depends_on:
      - reunionou.db

  # Service sql pour le stockage.
  # utilisé par l'api reunionou et l'api auth

  reunionou.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=reunionou
      - MYSQL_USER=reunionou_lbs
      - MYSQL_PASSWORD=reunionou_lbs
      - MYSQL_DATABASE=reunionou_lbs
    ports:
      - '3307:3306'
    networks:
      - reu.net
    volumes:
      - './reu_reunionou_service/sql:/var/sql'

  #
  # Service administration sql
  #

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "19180:80"
    links:
      - reunionou.db:db
    networks:
      - reu.net

  ######################################
  ###  AUTH Service : service d'authentification
  ###  API : api.auth
  ######################################
  api.auth:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.auth.local
      - VHOST_DOCROOT=/var/www/public/
    ports:
      - '19780:80'
      - '19743:443'
    volumes:
      - './reu_auth_service:/var/www'
    working_dir: /var/www/
    networks:
      - reu.net
    depends_on:
      - reunionou.db